# Generated by Django 3.2.7 on 2023-03-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230328_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '4. Brands'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['-date'], 'verbose_name_plural': '5. Cart Order'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'verbose_name_plural': '6. Cart Order Item'},
        ),
    ]
