# Generated by Django 3.2.18 on 2023-03-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.IntegerField(default=0.0),
        ),
    ]
