# Generated by Django 3.2.18 on 2023-03-30 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_review_helpful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful', to=settings.AUTH_USER_MODEL),
        ),
    ]
