# Generated by Django 3.2.18 on 2023-03-31 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230330_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfaq',
            options={'verbose_name_plural': 'Product Faqs'},
        ),
        migrations.AddField(
            model_name='productfaq',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_faq', to='store.product'),
        ),
    ]
