# Generated by Django 3.2.18 on 2023-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230330_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfaq',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfaq',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
