# Generated by Django 3.2.18 on 2023-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230331_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='delivery_status',
            field=models.CharField(choices=[('shipping', 'shipping'), ('shipped', 'shipped'), ('arrived', 'arrived'), ('collected', 'collected'), ('returning', 'returning'), ('returned', 'returned')], default='initiated', max_length=100),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'failed')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'failed'), ('refunding', 'refunding'), ('refunded', 'refunded'), ('unpaid', 'unpaid'), ('expired', 'expired')], default='initiated', max_length=100),
        ),
    ]
