# Generated by Django 3.2.18 on 2023-04-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230401_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='delivery_status',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('collected', 'Collected'), ('returning', 'Returning'), ('returned', 'Returned')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('opened', 'Opened'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=100),
        ),
    ]
