# Generated by Django 3.2.18 on 2023-04-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('store', '0020_cartorder_buyer_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='vendor.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
