# Generated by Django 3.2.18 on 2023-04-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20230403_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfaq',
            options={'verbose_name_plural': '7. Product Faqs'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': '8. Reviews/Rating'},
        ),
    ]
