# Generated by Django 3.2.18 on 2023-04-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_cartorder_service_fe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='service_fe',
            new_name='service_fee',
        ),
    ]
