# Generated by Django 3.2.18 on 2023-04-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_alter_vendor_user'),
        ('store', '0025_rename_service_fe_cartorder_service_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='vendor',
            field=models.ManyToManyField(related_name='seller', to='vendor.Vendor'),
        ),
    ]
