# Generated by Django 3.2.18 on 2023-04-05 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_alter_vendor_user'),
        ('store', '0027_cartorderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='vendor.vendor'),
        ),
    ]
