# Generated by Django 3.2.18 on 2023-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20230405_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
