# Generated by Django 3.2.18 on 2023-04-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20230405_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='product_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
