# Generated by Django 3.2.18 on 2023-04-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_stock_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
