# Generated by Django 3.2.18 on 2023-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20230406_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='delivery_status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('shipping_processing', 'Shipping Processing'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('returning', 'Returning'), ('returned', 'Returned')], default='on_hold', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('fulfilled', 'fulfilled'), ('partially_fulfilled', 'Partially Fulfilled'), ('cancelled', 'Cancelled')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='delivery_status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('shipping_processing', 'Shipping Processing'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('returning', 'Returning'), ('returned', 'Returned')], default='on_hold', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=1),
        ),
    ]
