# Generated by Django 3.2.18 on 2023-04-10 03:34

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20230409_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix=''),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
