# Generated by Django 3.2.18 on 2023-04-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20230409_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='buyer_shipping_address',
        ),
    ]
