# Generated by Django 3.2.18 on 2023-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_cartorder_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='paid_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
