# Generated by Django 3.2.18 on 2023-04-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0019_deliverycouriers'),
        ('store', '0044_cartorderitem_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='delivery_couriers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.deliverycouriers'),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
