# Generated by Django 3.2.18 on 2023-04-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20230412_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
