# Generated by Django 3.2.18 on 2023-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_cartorder_custom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('regular', 'regular'), ('auction', 'auction'), ('offer', 'offer')], default='regular', max_length=10),
        ),
    ]
