# Generated by Django 3.2.18 on 2023-04-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20230416_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbidders',
            options={'verbose_name_plural': '9 Product Bidders'},
        ),
        migrations.AlterField(
            model_name='productbidders',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productbidders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
    ]
