# Generated by Django 3.2.18 on 2023-04-16 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20230416_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfaq',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_faq', to='store.product'),
        ),
    ]
