# Generated by Django 3.2.18 on 2023-04-16 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0053_alter_productfaq_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bidders',
            field=models.ManyToManyField(blank=True, related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
    ]
