# Generated by Django 3.2.18 on 2023-04-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_product_bidders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
