# Generated by Django 3.2.18 on 2023-04-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_product_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbidders',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
