# Generated by Django 3.2.18 on 2023-04-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_productbidders_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_status',
            field=models.CharField(choices=[('on_going', 'On Going'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='on_going', max_length=10),
        ),
    ]
