# Generated by Django 3.2.18 on 2023-04-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0058_product_bidding_ended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbidders',
            options={'verbose_name_plural': '9. Product Bidders'},
        ),
        migrations.CreateModel(
            name='ProductOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_offer', to='store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '10. Product Bidders',
            },
        ),
    ]
