# Generated by Django 3.2.18 on 2023-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_auto_20230417_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbidders',
            options={'verbose_name_plural': '9 Product Bidders'},
        ),
        migrations.AlterModelOptions(
            name='productoffers',
            options={'verbose_name_plural': 'Product Offers'},
        ),
    ]
