# Generated by Django 3.2.18 on 2023-04-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_auto_20230418_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
