# Generated by Django 3.2.18 on 2023-04-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0021_basicaddon_send_email_notifications'),
        ('store', '0061_cartorderitem_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='order_description',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_tax', to='addons.taxrate'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='store.Category'),
        ),
    ]
