# Generated by Django 3.2.18 on 2023-04-24 22:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_auto_20230424_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=35, max_length=30, prefix='', unique=True),
        ),
    ]
