# Generated by Django 3.2.18 on 2023-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_auto_20230425_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfaq',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_faq', to='store.product'),
        ),
    ]
