# Generated by Django 3.2.18 on 2023-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_productfaq_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
