# Generated by Django 3.2.18 on 2023-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_review_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfaq',
            name='answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
