# Generated by Django 3.2.18 on 2023-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
    ]
