# Generated by Django 3.2.18 on 2023-05-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0032_auto_20230502_1422'),
        ('store', '0074_productoffers_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='earning',
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='delivery_couriers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.deliverycouriers'),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total of all amount listed above', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated Service Fee = service_fee * total (paid by buyer to platform)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated Shipping Fee = shipping_fee * total', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total of Product price * Product Qty', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Vendor Payable Earning Excluding Vendor Sales Fee', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated Vat based on delivery country = tax_rate * (total + shipping)', max_digits=12),
        ),
    ]
