# Generated by Django 3.2.18 on 2023-05-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0034_coupon_active'),
        ('store', '0075_auto_20230504_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.coupon'),
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon_discount_grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Grand Total after applying coupon', max_digits=12, null=True),
        ),
    ]
