# Generated by Django 3.2.18 on 2023-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0035_coupon_get_percent'),
        ('store', '0076_auto_20230506_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='vendor.Coupon'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendor.Vendor'),
        ),
    ]
