# Generated by Django 3.2.18 on 2023-05-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_cartorderitem_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='original_grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total of all amount listed above', max_digits=12),
        ),
    ]
