# Generated by Django 3.2.18 on 2023-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0042_auto_20230520_2041'),
        ('store', '0082_cartorder_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupon',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='vendor.Coupon'),
        ),
    ]
