# Generated by Django 3.2.18 on 2023-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_auto_20230520_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('old', 'Old'), ('2nd_hand', '2nd Hand'), ('old_2nd_hand', 'Old/2nd Hand')], default='new', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
