# Generated by Django 3.2.18 on 2023-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_auto_20230521_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_condition_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], default=1, null=True),
        ),
    ]
