# Generated by Django 3.2.18 on 2023-05-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0033_alter_basicaddon_header_type'),
        ('store', '0087_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='billing_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country_field', to='addons.taxrate'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_town_city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
