# Generated by Django 3.2.18 on 2023-05-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230523_0245'),
        ('store', '0088_auto_20230523_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='billing_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billingaddress'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='town_city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
