# Generated by Django 3.2.18 on 2023-05-26 02:01

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_auto_20230526_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='SKU', unique=True),
        ),
    ]
