# Generated by Django 3.2.18 on 2023-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Wallet Points', 'Wallet Points')], max_length=100, null=True),
        ),
    ]
