# Generated by Django 3.2.18 on 2023-05-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_auto_20230526_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Cart Order'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Cart Order Item'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbidders',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product Bidders'},
        ),
        migrations.AlterModelOptions(
            name='productfaq',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product Faqs'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Reviews & Rating'},
        ),
    ]
