# Generated by Django 3.2.18 on 2023-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_auto_20230526_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_section_featured',
            field=models.BooleanField(default=False),
        ),
    ]
