# Generated by Django 3.2.18 on 2023-06-05 22:45

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_product_hero_section_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('old_2nd_hand', '“Used or 2nd Hand'), ('custom', 'Custom')], default='new', max_length=50, null=True),
        ),
    ]
