# Generated by Django 3.2.18 on 2023-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Address'},
        ),
        migrations.AddField(
            model_name='address',
            name='same_as_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
