# Generated by Django 3.2.18 on 2023-05-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0033_alter_basicaddon_header_type'),
        ('core', '0009_auto_20230522_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_country', to='addons.taxrate'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country', to='addons.taxrate'),
        ),
    ]
