# Generated by Django 3.2.18 on 2023-04-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0026_notification_seen'),
        ('reports', '0002_biddinguserreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vendor_report', to='vendor.vendor'),
        ),
    ]
