# Generated by Django 3.2.18 on 2023-05-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_generalissue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalissue',
            options={'verbose_name_plural': 'General Report'},
        ),
    ]
