# Generated by Django 3.2.18 on 2023-03-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0005_auto_20230330_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='general_tax_percentage',
            field=models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)'),
        ),
    ]
