# Generated by Django 3.2.18 on 2023-04-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0006_basicaddon_general_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
