# Generated by Django 3.2.18 on 2023-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0008_auto_20230404_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='vendor_fee_percentage',
            field=models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)'),
        ),
    ]
