# Generated by Django 3.2.18 on 2023-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0009_basicaddon_vendor_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='service_fee_charge_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate')], default='percentage', max_length=30),
        ),
        migrations.AddField(
            model_name='basicaddon',
            name='service_fee_flat_rate',
            field=models.IntegerField(default=5, help_text='NOTE: Add the amount you want to charge as service fee e.g $2.30'),
        ),
        migrations.AlterField(
            model_name='basicaddon',
            name='service_fee_percentage',
            field=models.IntegerField(default=5, help_text='NOTE: Numbers added here are in percentage (%)ve.g 4%'),
        ),
    ]
