# Generated by Django 3.2.18 on 2023-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0012_taxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.CharField(choices=[('classic', 'Classic'), ('dynamic', 'Dynamic')], default='classic', max_length=50)),
            ],
        ),
    ]
