# Generated by Django 3.2.18 on 2023-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0014_policy_registration_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegType',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='registration_form',
        ),
        migrations.AddField(
            model_name='basicaddon',
            name='registration_form_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('dynamic', 'Dynamic')], default='classic', max_length=50),
        ),
    ]
