# Generated by Django 3.2.18 on 2023-04-19 13:23

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_auto_20230418_2200'),
        ('vendor', '0020_alter_deliverycouriers_couriers_tracking_website_address'),
        ('addons', '0015_auto_20230418_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_for_logged_in_users', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active_for_logged_in_user', models.BooleanField(default=False)),
                ('announcement_for_not_logged_in_users', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active_for_not_logged_in_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(blank=True, null=True)),
                ('share', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='PlatformNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications')),
                ('title', models.CharField(max_length=1000)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SuperUserSignUpPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='17880984243324543', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Video Links', max_length=100)),
                ('how_to_use_platform', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('how_to_use_affiliate_system', models.URLField(blank=True, default='https://youtube.com', null=True)),
                ('how_to_become_a_vendor', models.URLField(blank=True, default='https://youtube.com', null=True)),
            ],
            options={
                'verbose_name': 'Tutorial Video',
                'verbose_name_plural': 'Tutorial Video',
            },
        ),
        migrations.AddField(
            model_name='earningpoints',
            name='referral_point',
            field=models.PositiveIntegerField(default=500, help_text='Enter an amount that user will get when they refer thier friend'),
        ),
        migrations.AddField(
            model_name='earningpoints',
            name='text',
            field=models.CharField(default='Point', max_length=10),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklnopqstuv', length=20, max_length=25, prefix='')),
                ('topic', models.CharField(choices=[('talk_to_an_agent ', 'Talk To An Agent '), ('complaint', 'Complaint'), ('report_product', 'Report Product'), ('report_vendor', 'Report Vendor'), ('new_feature_idea', 'New Feature Idea')], default='talk_to_an_agent', max_length=50)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Contact Us ',
            },
        ),
    ]
