# Generated by Django 3.2.18 on 2023-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0016_auto_20230419_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Support Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='platformnotifications',
            options={'ordering': ['date'], 'verbose_name': 'Platform Update Notifications', 'verbose_name_plural': 'Platform Update Notifications'},
        ),
    ]
