# Generated by Django 3.2.18 on 2023-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0018_auto_20230419_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontactinformation',
            name='working_days',
            field=models.CharField(blank=True, default='Monday - Friday', max_length=1000, null=True),
        ),
    ]
