# Generated by Django 3.2.18 on 2023-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0021_basicaddon_send_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='custom_name',
            field=models.CharField(blank=True, default='Tax', max_length=100, null=True),
        ),
    ]
