# Generated by Django 3.2.18 on 2023-04-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0022_taxrate_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='payout_vendor_fee_immediately',
            field=models.BooleanField(default=True),
        ),
    ]
