# Generated by Django 3.2.18 on 2023-04-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0026_basicaddon_homepage_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesetup',
            name='static',
            field=models.BooleanField(default=False),
        ),
    ]
