# Generated by Django 3.2.18 on 2023-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0027_homepagesetup_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_type',
            field=models.CharField(choices=[('use_image ', 'Use Company Image'), ('use_name ', 'Use Company Name')], default='use_image', max_length=30),
        ),
    ]
