# Generated by Django 3.2.18 on 2023-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0028_company_logo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='image_upload_limit',
            field=models.IntegerField(default=10),
        ),
    ]
