# Generated by Django 3.2.18 on 2023-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0029_basicaddon_image_upload_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='review_type',
            field=models.CharField(choices=[('any_authenticated_user ', 'Allow any user that is logged in to review a product'), ('only_purchased_user ', 'Allow only users who have purchased a product to review the product')], default='any_authenticated_user', max_length=130),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_type',
            field=models.CharField(choices=[('use_image ', 'Use Company Image'), ('use_name ', 'Use Company Name'), ('use_landscape ', 'Use Landscape Image')], default='use_image', max_length=30),
        ),
    ]
