# Generated by Django 3.2.18 on 2023-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0030_auto_20230505_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='view_more',
            field=models.CharField(default='View All', max_length=10),
        ),
    ]
