# Generated by Django 3.2.18 on 2023-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0031_basicaddon_view_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='header_type',
            field=models.CharField(choices=[(1, 'Header 1'), (2, 'Header 2')], default=1, max_length=130),
        ),
    ]
