# Generated by Django 3.2.18 on 2023-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0032_basicaddon_header_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicaddon',
            name='header_type',
            field=models.CharField(choices=[('1', 'Header 1'), ('2', 'Header 2')], default='1', max_length=130),
        ),
    ]
