# Generated by Django 3.2.18 on 2023-05-26 16:57

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0033_alter_basicaddon_header_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ABout Us',
                'verbose_name_plural': 'ABout Us',
            },
        ),
    ]
