# Generated by Django 3.2.18 on 2023-05-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0034_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
