# Generated by Django 3.2.18 on 2023-05-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0035_alter_aboutus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesetup',
            name='active',
        ),
        migrations.RemoveField(
            model_name='homepagesetup',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='homepagesetup',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='homepagesetup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagesetup',
            name='static',
        ),
        migrations.RemoveField(
            model_name='homepagesetup',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='homepagesetup',
            name='homepage_type',
            field=models.CharField(choices=[('1', 'Homepage 1'), ('2', 'Homepage 2'), ('3', 'Homepage 3'), ('4', 'Homepage 4')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicaddon',
            name='homepage_style',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('static', 'Static')], default='carousel', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepagesetup',
            name='title',
            field=models.CharField(default='Home Page Setup', max_length=50),
        ),
        migrations.CreateModel(
            name='Home_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage')),
                ('small_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('main_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('sub_title', models.CharField(default='Lorem Ipsum is the best way of writing destiny car type', max_length=1010)),
                ('button_text', models.CharField(default='Visit PRoducts', max_length=100)),
                ('button_url', models.URLField(default='https://Desphixs.com/shop/', max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.homepagesetup')),
            ],
            options={
                'verbose_name_plural': 'Home Two',
            },
        ),
        migrations.CreateModel(
            name='Home_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage')),
                ('small_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('main_title', models.CharField(default='Keep your new born baby engaged', max_length=1010)),
                ('sub_title', models.CharField(default='Lorem Ipsum is the best way of writing destiny car type', max_length=1010)),
                ('button_text', models.CharField(default='Visit PRoducts', max_length=100)),
                ('button_url', models.URLField(default='https://Desphixs.com/shop/', max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons.homepagesetup')),
            ],
            options={
                'verbose_name_plural': 'Home One',
            },
        ),
    ]
