# Generated by Django 3.2.18 on 2023-05-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0038_home_one_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicaddon',
            name='homepage_style',
        ),
    ]
