# Generated by Django 3.2.18 on 2023-06-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0039_remove_basicaddon_homepage_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicaddon',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('Cash On Delivery', 'Cash On Delivery')], default='PayPal', max_length=130),
        ),
    ]
