# Generated by Django 3.2.18 on 2023-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0040_basicaddon_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Basic Addons',
                'verbose_name_plural': 'Basic Addons',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='basicaddon',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='basicaddon',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='addons.PaymentMethod'),
        ),
    ]
