# Generated by Django 3.2.18 on 2023-06-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0041_auto_20230604_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-date'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Method'},
        ),
    ]
